# Generated by Django 4.1.1 on 2022-09-10 11:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, verbose_name='주문날짜')),
                ('pay_state', models.CharField(choices=[('결제완료', 0), ('결제취소', 1)], max_length=4, verbose_name='결제상태')),
                ('order_state', models.CharField(choices=[('결제취소', 0), ('상품준비중', 1), ('상품출고', 2), ('배송중', 3), ('배송완료', 4)], default=0, max_length=5, verbose_name='주문상태')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='수량')),
                ('price', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000000)], verbose_name='상품 가격')),
                ('buyr_name', models.CharField(max_length=10, null=True, verbose_name='구매자')),
                ('buyr_city', models.CharField(max_length=20, verbose_name='구매자 도시')),
                ('buyr_country', models.CharField(max_length=5, verbose_name='구매자 국가')),
                ('buyr_zipx', models.CharField(max_length=20, verbose_name='구매자 우편번호')),
                ('vccode', models.CharField(max_length=10, verbose_name='나라별 decode')),
                ('delivery_num', models.CharField(max_length=10, null=True, verbose_name='송장번호')),
                ('start_at', models.DateField(auto_now_add=True, verbose_name='주문시작일자')),
                ('end_at', models.DateField(auto_now=True, verbose_name='주문종료일자')),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons.coupon', verbose_name='쿠폰')),
                ('delivery_cost', models.ForeignKey(db_column='delivery_cost', null=True, on_delete=django.db.models.deletion.PROTECT, to='deliveries.deliverycost', verbose_name='배송비')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
