# Generated by Django 4.1.1 on 2022-09-14 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_coupon_value'),
        ('orders', '0003_rename_price_order_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(db_column='coupon', null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons.coupon', verbose_name='쿠폰'),
        ),
    ]
