from django.db import models
from django.core.validators import MaxValueValidator


class CountryCode(models.Model):
    country_idx = models.BigAutoField(primary_key=True)
    country_code = models.CharField(max_length=2)
    country_dcode = models.CharField(max_length=5, null=True)
    country_name = models.CharField(max_length=30)

    class Meta:
        db_table = 'country_code'

    def __str__(self):
        return self.country_name


class DeliveryCost(models.Model):
    id = models.BigAutoField(primary_key=True)
    quantity = models.PositiveIntegerField(validators=[MaxValueValidator(72)], verbose_name='수량')
    Australia = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Brazil = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Canada = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    China = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    France = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Germany = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Hong_kong = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Indonesia = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Japan = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Malaysia = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    New_Zealand = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Philippines = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Russia = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Singapore = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Spain = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Taiwan = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Thailand = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    UK = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    USA = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Vietnam = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Cambodia = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Laos = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Macao = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Mongolia = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Myanmar = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Bangladesh = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Bhutan = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Brunei_Darussala = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    India = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Maldives = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Nepal = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Sri_Lanka = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Albania = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Armenia = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Austria = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Azerbaijan = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Bahrain = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Belarus = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Belgium = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Bulgaria = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Bosnia_And_Herzegovina = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Croatia = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Cyprus = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Czech_Rep = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Denmark = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Estonia = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Finland = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Georgia = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Greece = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Hungary = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Iran = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Ireland = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Israel = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Jordan = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Kazakhstan = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Latvia = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Luxembourg = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Macedonia = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Netherlands = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Norway = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Oman = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Pakistan = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Poland = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Portugal = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Qatar = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Romania = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Saudi_Arabia = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Slovakia = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Slovenia = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Sweden = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Switzerland = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Turkey = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Ukraine = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    United_Arab_Emirates = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Uzbekistan = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Algeria = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Antiless_Netherlands = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Argentina = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Botswana = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Cape_Verde = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Chile = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Costa_Rica = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Cuba = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Djibouti = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Dominican_Republic = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Ecuador = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Egypt = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Eritrea = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Ethiopia = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Fiji = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Kenya = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Lesotho = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Mauritius = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Mexico = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Morocco = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Mozambique = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Nigeria = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Panama = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Peru = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Rwanda = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Tanzania = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Tunisia = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])
    Zambia = models.PositiveIntegerField(validators=[MaxValueValidator(426500)])

    class Meta:
        db_table = 'delivery_cost'

    def __str__(self):
        return self.id
