# Generated by Django 4.1.1 on 2022-09-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_coupon_active_coupon_num_available_coupon_num_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='type',
            field=models.CharField(choices=[('정액할인', 0), ('배송비 할인', 1), ('%할인', 2)], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='num_available',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
