# Generated by Django 4.1.1 on 2022-09-11 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_coupon_type_alter_coupon_num_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.PROTECT, to='coupons.coupontype'),
        ),
    ]
