# Generated by Django 4.1.1 on 2022-09-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_alter_coupon_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimedcoupon',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
