# Generated by Django 4.1.1 on 2022-09-11 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_coupontype_remove_coupon_discount_alter_coupon_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coupontype',
            table='coupon_type',
        ),
    ]
